### ISSUE TITLE
gauge/counter

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-oam-yang#15]
Please check when it makes sense to use a gauge rather than a counter. For example:

    +--ro num-event-avg?     yang:counter32

**Comment by fno2010** [comment]
Good point. `yang:gauge64` seems more reasonable.

**Comment by boucadair** [comment]
Thanks. 

BTW, is there any reason all the counters are 32? may be moved those to be 64.

**Comment by fno2010** [comment]
Initially, we just thought 32 might be enough for the current deployment. But I agree. 64 will be better. I also think we should use 64.

**Comment by boucadair** [comment]
Reopening as I think the type has to be reassessed for some other data nodes (e.g., res-mem-size). 

If the value may increase/decrease, then gauge64 should be used.

**Comment by fno2010** [comment]
Yes, you are right. I will check all the statistics data nodes to fix their types.

I think the following nodes should use gauge64 at least:

- memory utilization
- number of living connections
- statistics in the last time window

**Comment by fno2010** [comment]
Track suggestions from yangdoctors early review by Andy:

### 5 minute counters

- Should be type gauge64, not counter64 because the value can go down.

  - num-total-last-req
  - num-total-last-succ
  - num-total-last-fail

### size counters

- Should be type uint64, not counter64 because the value is a size.

  - res-mem-size
  - res-enc-size

### update event counters

- It is not clear what the correct data type should be. Not counter64.

  - num-event-max
  - num-event-min

- Are these leafs maintained over a 5 minute interval perhaps?
  Then they should be gauge64.

- The procedure to determine min and max should be specified or referenced.

**Comment by fno2010** [comment]
`uint` should always be safe. But maybe `gauge` provides more semantics? I think either work.

About the time interval, yes, it is configured by `time-window-size`. But `num-event-*` shows the total value, not the value in a given time interval. We just added a collection of stats `num-event-*-last` to provide values in the last time interval.

**Comment by fno2010** [comment]
Changed type of `num-total-last-*` to `gauge64`:

https://github.com/ietf-wg-alto/draft-ietf-alto-oam-yang/blob/5dea617f7e681a51666c173adab7c575bc1cbb23/yang/ietf-alto-stats.yang#L85-L102

Changed type of `res-*-size` to `uint64`:

https://github.com/ietf-wg-alto/draft-ietf-alto-oam-yang/blob/5dea617f7e681a51666c173adab7c575bc1cbb23/yang/ietf-alto-stats.yang#L129-L140

Changed type of `num-event-*` to `gauge64` (Qin suggests to simply using `uint32`) and updated the descriptions:

https://github.com/ietf-wg-alto/draft-ietf-alto-oam-yang/blob/5dea617f7e681a51666c173adab7c575bc1cbb23/yang/ietf-alto-stats.yang#L198-L228

`num-event-*-last` are added to provide stats within the last time window:

https://github.com/ietf-wg-alto/draft-ietf-alto-oam-yang/blob/5dea617f7e681a51666c173adab7c575bc1cbb23/yang/ietf-alto-stats.yang#L229-L266
