### ISSUE TITLE
Notifications when some resource limits are reached

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-oam-yang#18]
I wonder whether you considered having notifications in the module that are triggered when some thresholds are fired.

**Comment by QiufangMa** [comment]
I see it more complete if some notifications could be triggered when some value is crossing a secure threshold, but instead of defining the threshold-related parameters inside the YANG module, would it be better and simpler to state in the document that  alarm notification defined in RFC 8632 could be reused to receive alarms when metrics exceed or fall below some thresholds?

**Comment by fno2010** [comment]
Interesting idea. If some notifications could be reused, it would be great. I am not familiar with RFC 8632. Just quickly checked it. It seems to be very complex. We may need to carefully check which parts can be reused. Do you have any suggestions?

**Comment by QiufangMa** [comment]
If the related threshold and notification have already been defined, I believe we can go with that.
I just don' think it a scalable way to define threshold configuration in each YANG module, but can achieve the goal, anyway.
