### ISSUE TITLE
Assess if cost grouping structure is not too tight to ALTO 

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-oam-yang#34]
keep in mind that some of the groupings can be used by others (e.g., cats)

**Comment by fno2010** [comment]
Hi Med,

This is a very interesting topic. I checked the chat history in zulip (https://zulip.ietf.org/#narrow/stream/cats). But I just wonder if this work should be done in YANG. In ALTO O&M YANG modules, only identities of cost modes and metrics are defined. Because these YANG modules are only used to configure how the ALTO information resources will generate the cost values, but not deliver actual cost values using YANG. That means we don't have any `typedef` for cost values.

Jensen

**Comment by boucadair** [comment]
I'm not sure, either. An aspect that I wanted we check is to what extent related groupings in the alto module are reusable by others (cats, for example).
